### ISSUE TITLE
paper source

### ISSUE THREAD

**Issue by edgarriba** [yuruntian/L2-Net#1]
@yuruntian where we can find the paper for this repository?

**Comment by yuruntian** [comment]
@edgarriba I will put the paper on arxive recently, or if you want see the paper soon,  leave your email address, I can send you the pre-print.

**Comment by edgarriba** [comment]
oh cool,
edgar dot riba at gmail dot com

**Comment by ducha-aiki** [comment]
http://www.nlpr.ia.ac.cn/fanbin/pub/L2-Net_CVPR17.pdf
