### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by ducha-aiki** [yuruntian/L2-Net#2]
Hi,

When are you planning to release your model? Is it possible to get it privately?

**Comment by edgarriba** [comment]
@ducha-aiki would be nice to see a Pytorch implementation! You can use the tools I setup for the triplet :smile:

**Comment by ducha-aiki** [comment]
@edgarriba well, it is often hard to reproduce author`s results, you know :P 
But if I will train this, I will definitely put it on github :)

**Comment by edgarriba** [comment]
nice!

**Comment by yuruntian** [comment]
@edgarriba @ducha-aiki pre-trained models have been uploaded.
The training code is need to be reorginazed, which needs a lot of time, 
I am busy at other experiment recently (not in the mood of rewriting old codes :) ), but the training code will be availiable.

**Comment by ducha-aiki** [comment]
@yuruntian Thank you a lot!
