### ISSUE TITLE
How do you confirm the feature vector outputed from LRN will be a unit vector

### ISSUE THREAD

**Issue by xuelunshen** [yuruntian/L2-Net#7]
Paper writed this sentence "we use a Local Response Normalization layer (LRN) as the output layer to produce unit descriptors."

So, I want to know is it definitly get a unit feature vector from the LRN ?

**Comment by yuruntian** [comment]
@Xylon-Sean for example in pytorch : nn.LocalResponseNorm(2*self.dim_desc, alpha=2*self.dim_desc, beta=0.5, k=0)

**Comment by xuelunshen** [comment]
@yuruntian thank you, I trid these code and it produced the unit descriptors.
